In [1]:
list=["apple","orange","pineapple"]

In [2]:
print(list)

['apple', 'orange', 'pineapple']


In [3]:
print(len(list))

3


In [4]:
print((type(list)))

<class 'list'>


In [5]:
list=["apple","orange","pineapple","apple"] #can add duplicate values

In [10]:
x=[1,2,3,4,5]
print(x)

[1, 2, 3, 4, 5]


In [12]:
print(x[2])

3


In [24]:
x=[1,2,3,4,5]
x.append(3)
print(x)

[1, 2, 3, 4, 5, 3]


In [26]:
x.pop(3)
print(x)

[1, 2, 3, 5]


In [28]:
x.clear()
print(x)

[]


In [35]:
x=["apple","orange"]
y=x.copy()
print(x)

['apple', 'orange']


In [40]:
x=[1,2,3,4]
print(x.count(2))

1


In [42]:
a=[1,2,3]
b=[4,5,6]
a.extend(b)
print(a)

[1, 2, 3, 4, 5, 6]


In [43]:
x.insert(3,4)

In [44]:
print(x)

[1, 2, 3, 4, 4]


In [48]:
x.sort()

In [49]:
print(x)

[1, 3]


In [55]:
x=[1,2,3,4,5,6,7,8,9]
list
np_array=np.array(list)
np_array

array(['apple', 'orange', 'pineapple', 'apple'], dtype='<U9')

In [60]:
list=[1,2,3,4,5,6,7,8,9]
list
np_array=np.array(list)
np_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
import numpy as np
rows=3
columns=3
list_of_list=[[j for j in range(columns)]for i in range(rows)]
list_of_list

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [69]:
import numpy as np
rows=3
columns=3

list_of_list=[[j for j in range(columns)]for i in range(rows)]
list_of_list

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [73]:
import numpy as np
rows=3
columns=3
dig=3
list_of_list=[[[k for k in range(dig)]for j in range(columns)]for i in range(rows)]
list_of_list

[[[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
 [[0, 1, 2], [0, 1, 2], [0, 1, 2]]]

In [75]:
import numpy as np
array_1=[1,2,3,4]
array_2=[5,6,7,8]
array_3=[9,1,3,5]

array_3d=np.array([array_1,array_2,array_3])
array_3d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 3, 5]])

In [76]:
#create an evenly spaced array of numbers based on given start and stop values

import numpy as np

start = 0
stop = 10
num = 5

arr = np.linspace(start, stop, num)
print(arr)


[ 0.   2.5  5.   7.5 10. ]


In [77]:
#create an  array of zeros that be filled with data later
import numpy as np

arr = np.zeros(5)

print(arr)



[0. 0. 0. 0. 0.]


In [84]:
#create an array of ones
import numpy as np
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [80]:
#create array of rand,floats between zero and one
import numpy as np

arr = np.random.rand(5)

print(arr)



[0.73093044 0.34159369 0.5123652  0.17734053 0.21821032]


In [85]:
#create 1d array and insert the values 1,2,3,,5 and access the following elements:1st element,2nd element,range of elements from 1st to 3rd,range of elements from 2nd element,range of elements from index=-2 

import numpy as np

# Create the array

arr = np.array([1, 2, 3, 5])

# 1st element (index 0)
first_element = arr[0]

# 2nd element (index 1)
second_element = arr[1]

# Range of elements from 1st to 3rd (index 0 to 2, inclusive of start, exclusive of stop)
range_1_to_3 = arr[0:3]

# Range of elements from 2nd element to the end (index 1 to end)
range_from_2nd = arr[1:]

# Range of elements from index = -2 to the end (negative index counts from the end)
range_from_neg2 = arr[-2:]

print("1st element:", first_element)
print("2nd element:", second_element)
print("Range from 1st to 3rd element:", range_1_to_3)
print("Range from 2nd element to end:", range_from_2nd)
print("Range from index -2 to end:", range_from_neg2)


1st element: 1
2nd element: 2
Range from 1st to 3rd element: [1 2 3]
Range from 2nd element to end: [2 3 5]
Range from index -2 to end: [3 5]


In [89]:
#create 2d array and try to access following elements:1st row and 2nd column element,2nd row elements,3rd row column elements,range of elements in 1st and 2nd row with 2nd and 3rd column

# Create a 2D array (list of lists)
array_2d = [
    [1, 2, 3, 4],       # 1st row
    [5, 6, 7, 8],       # 2nd row
    [9, 10, 11, 12]     # 3rd row
]

# Access 1st row, 2nd column element (rows and columns are 0-indexed)
element_1st_row_2nd_col = array_2d[0][1]  # 2

# Access 2nd row elements
elements_2nd_row = array_2d[1]  # [5, 6, 7, 8]

# Access 3rd row elements
elements_3rd_row = array_2d[2]  # [9, 10, 11, 12]

# Access range of elements in 1st and 2nd row, 2nd and 3rd columns
range_1st_2nd_row_2nd_3rd_col = [row[1:3] for row in array_2d[0:2]]  # [[2, 3], [6, 7]]

(element_1st_row_2nd_col, elements_2nd_row, elements_3rd_row, range_1st_2nd_row_2nd_3rd_col)


(2, [5, 6, 7, 8], [9, 10, 11, 12], [[2, 3], [6, 7]])

In [90]:
#craete a 1d array make it within order  by axis wise.

import numpy as np

# Create a 1D array with unordered elements
arr = np.array([5, 3, 9, 1, 7])

# Sort the array to order it axis-wise (in ascending order)
arr_sorted = np.sort(arr)

print("Original array:", arr)
print("Sorted array:", arr_sorted)


Original array: [5 3 9 1 7]
Sorted array: [1 3 5 7 9]


In [91]:
#read 1d array and insert the values 1,9,2,5,3 and check whether the elements in array are greater than 5.and print those elements as separate list(use boolean masking)

import numpy as np

# Create 1D NumPy array with given values
arr = np.array([1, 9, 2, 5, 3])

# Boolean mask for elements greater than 5
mask = arr > 5

# Filter elements based on mask
filtered_elements = arr[mask]

print("Original array:", arr)
print("Elements greater than 5:", filtered_elements.tolist())  # convert to list for separate list output


Original array: [1 9 2 5 3]
Elements greater than 5: [9]


In [ ]:
#create 1d array and  insert values from 0 to 20 withion 3 gap space and find the values which are divided by and replace 0 in array which are not satisfied the condition